name: Cypress tests
on:
  push:
    branches-ignore:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run: npm ci
      - run: npx cypress verify
      - save_cache:
        key: cache-{{ checksum "package.json" }}
        paths:
          - ~/.npm
          - ~/.cache
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
